import { Avatar } from "@neuralbertatech/react";
import Head from "next/head";
import type { NextPage } from "next";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Notifications</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={ {
        width: "100vw",
        height: "100vh"
      } }>
        <Avatar src="https://picsum.photos/200" alt="Joe Bloggins" />
      </main>
    </div>
  );
};

export default Home;
