import { Button, Card, CardBody, CardButtons } from "@neuralbertatech/react";
import { useEffect, useState } from "react";

import Head from "next/head";
import type { NextPage } from "next";

const Home: NextPage = () => {
  type Optional<T> = T | undefined;
  const [date, setDate] = useState<Optional<Date>>(undefined);
  useEffect(() => {
    setDate(new Date());
  }, []);
  const cards = [1, 2, 3, 4];
  return (
    <>
      <Head>
        <title>Notifications</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{
        padding: "32px"
      }}>
        {cards.map(i => <Card
          glass
          title={`Title ${i}`}
          subtitle={`Subtitle ${i}`}
          date={date}
          key={i}
        >
          <CardBody>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa eveniet id laboriosam dolorum aliquam dignissimos officia enim est repudiandae. Excepturi ducimus qui at eum rem, a fugiat vitae voluptates aut?
          </CardBody>
          <CardButtons orientation="horizontal">
            <Button text="Button 1" href="/cards" style={{width: "100%"}} outlined></Button>
            <Button text="Button 2" href="/cards" style={{width: "100%"}} outlined></Button>
            <Button text="Button 3" href="/cards" style={{width: "100%"}}></Button>
          </CardButtons>
        </Card>)}
      </main>
    </>
  );
};

export default Home;
