import { Button, InputEmail, InputNumber, InputPassword, InputText } from "@neuralbertatech/react";
import { DEFAULT_INPUT_STATE_NUMBER, DEFAULT_INPUT_STATE_STRING } from "@neuralbertatech/react/lib/components/input/InputBase";
import { useEffect, useState } from "react";

import Head from "next/head";
import type { InputState } from "@neuralbertatech/react/lib/components/input/InputBase";
import type { NextPage } from "next";

interface Form {
  name: InputState<string>;
  email: InputState<string>;
  age: InputState<number>;
}

const Home: NextPage = () => {
  const [name, setName] = useState<InputState<string>>(DEFAULT_INPUT_STATE_STRING);
  const [email, setEmail] = useState<InputState<string>>(DEFAULT_INPUT_STATE_STRING);
  const [password, setPassword] = useState<InputState<string>>(DEFAULT_INPUT_STATE_STRING);
  const [age, setAge] = useState<InputState<number>>(DEFAULT_INPUT_STATE_NUMBER);
  const [form, setForm] = useState<Form>({
    name,
    email,
    age,
  });
  const [disableButton, setDisableButton] = useState(true);

  useEffect(() => {
    const tempForm = {
      name,
      email,
      age,
    };
    setForm(tempForm);
    setDisableButton(Object.values(tempForm)
      .some((value) => value.valid === false));
  }, [name, email, age]);

  return (
    <div>
      <Head>
        <title>Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{
        width: "100vw",
        height: "100vh"
      }}>
        <form>
          <InputText label="Name" name="name" placeholder="Boaty McBoatface" validation={/\w+\s\w+/} state={[name, setName]} icon={<span>🔍</span>} required />
          <InputEmail label="Email" name="email" placeholder="example@neuralberta.tech" state={[email, setEmail]} required />
          <InputPassword label="Password" name="password" placeholder="example@neuralberta.tech" state={[password, setPassword]} required />
          <InputNumber label="Age" name="age" placeholder="Email" state={[age, setAge]} min={0} max={5} required />
        </form>
        <Button text="Log" onClick={() => console.table(form)} disabled={disableButton} />
      </main>
    </div>
  );
};

export default Home;
