import type { NextPage } from "next";
import Head from "next/head";
import InputText from "@neuralbertatech/react/lib/InputText";
import InputEmail from "@neuralbertatech/react/lib/InputEmail";
import InputNumber from "@neuralbertatech/react/lib/InputNumber";
import { InputState } from "../../lib/utils/inputBase";
import Button from "@neuralbertatech/react/lib/Button";
import { useEffect, useState } from "react";

interface Form {
  name: InputState<string>;
  email: InputState<string>;
  age: InputState<number>;
}

const Home: NextPage = () => {
  const [name, setName] = useState<InputState<string>>({
    value: "",
  });
  const [email, setEmail] = useState<InputState<string>>({
    value: "",
  });
  const [age, setAge] = useState<InputState<number>>({
    value: 0,
  });
  const [form, setForm] = useState<Form>({
    name,
    email,
    age,
  });
  const [disableButton, setDisableButton] = useState(true);

  useEffect(() => {
    const tempForm = {
      name,
      email,
      age,
    };
    setForm(tempForm);
    setDisableButton(Object.values(tempForm)
      .some((value) => value.valid === false));
  }, [name, email, age]);

  return (
    <div>
      <Head>
        <title>Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{
        width: "100vw",
        height: "100vh"
      }}>
        <form>
          <label>Name</label>
          <InputText placeholder="Boaty McBoatface" validation={/\w+\s\w+/} state={[name, setName]} />
          <label>Email</label>
          <InputEmail placeholder="example@neuralberta.tech" state={[email, setEmail]} />
          <label>Age</label>
          <InputNumber placeholder="Email" state={[age, setAge]} min={0} max={5} />
        </form>
        <Button text="Log" onClick={() => console.table(form)} disabled={disableButton} />
      </main>
    </div>
  );
};

export default Home;
