import Head from "next/head";
import type { NextPage } from "next";
import { Radio } from "@neuralbertatech/react";

//import { useEffect, useState } from "react";


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Radio Button</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{
        padding: "32px"
      }}>
        
        <Radio text="Option 1" name="radio-test" style={{padding: "10px"}}></Radio>
        <Radio text="Option 2" name="radio-test" style={{padding: "10px"}}></Radio>
        <Radio text="Disabled Option" name="radio-test" disabled style={{padding: "10px"}}></Radio>
      </main>
    </>
  );
};

export default Home;
